import Head from 'next/head';

import Form from '../components/form';

import { useState } from 'react';

/*import {BiUserPlus} from 'react-icons'*/
import { BiUserPlus } from "react-icons/bi";

import Table from'../components/table';


export default function Home(){
     const [visible, setValue]=useState(false)

     const handler =() =>{
      setValue(visible?false :true )
     }
  return (
<section>
<Head>
        <title>Brand Sale List </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <main className='py-5'>
        <h1 className='text-xl md: text-5xl text-center font-bold py-10'>BrandSale List </h1>

      <div className='container mx-auto flex justify-between py-5 border-b'>
         <div className='left flex gap-3.5'>
           <button onClick={handler}className='flex bg-red-300 text-black px-4 py-2 border rounded-md hover:bg-slate-500 '>
             Add Row <span className='px-1'><BiUserPlus size={23}></BiUserPlus></span>
           </button>
         </div>

</div>



{visible ? <Form></Form>:<></>}



    

     <div className='container mx-auto'>
      <Table>

      </Table>
     </div>



      </main>
    </section>
  )
}

