import Head from 'next/head'

/*import {BiUserPlus} from 'react-icons'*/
import { BiUserPlus } from "react-icons/bi";



export default function Home() {
  return (
<section>
<Head>
        <title>Brand Sale List </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <main className='py-5'>
        <h1 className='text-xl md: text-5xl text-center font-bold py-10'>BrandSale List </h1>

      <div className='container mx-auto flex justify-between py-5 border-b'>
         <div className='left flex gap-3.5'>
           <button className='flex bg-red-300 text-black px-4 py-2 border rounded-md hover:bg-slate-500 '>
             Add Row <span className='px-1'><BiUserPlus size={23}></BiUserPlus></span>
           </button>
         </div>

      /*form */


      /* table */

          




             
      </div>






      </main>
    </section>
  )
}
